/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'taim1\'">' + entity + '</span>' + html;
	}
	var icons = {
			'imi-home' : '&#xe000;',
			'imi-tags' : '&#xe001;',
			'imi-calendar' : '&#xe002;',
			'imi-lab' : '&#xe003;',
			'imi-fire' : '&#xe004;',
			'imi-mug' : '&#xe005;',
			'imi-stats' : '&#xe006;',
			'imi-pie' : '&#xe007;',
			'imi-bars' : '&#xe008;',
			'imi-wand' : '&#xe009;',
			'imi-settings' : '&#xe00a;',
			'imi-wrench' : '&#xe00b;',
			'imi-unlocked' : '&#xe00c;',
			'imi-lock' : '&#xe00d;',
			'imi-key' : '&#xe00e;',
			'imi-smiley' : '&#xe00f;',
			'imi-smiley-2' : '&#xe010;',
			'imi-sad' : '&#xe011;',
			'imi-sad-2' : '&#xe012;',
			'imi-thumbs-up' : '&#xe013;',
			'imi-thumbs-up-2' : '&#xe014;',
			'imi-star' : '&#xe015;',
			'imi-star-2' : '&#xe016;',
			'imi-star-3' : '&#xe017;',
			'imi-brightness-contrast' : '&#xe018;',
			'imi-brightness-medium' : '&#xe019;',
			'imi-bookmarks' : '&#xe01a;',
			'imi-eye' : '&#xe01b;',
			'imi-eye-blocked' : '&#xe01c;',
			'imi-attachment' : '&#xe01d;',
			'imi-flag' : '&#xe01e;',
			'imi-link' : '&#xe01f;',
			'imi-earth' : '&#xe020;',
			'imi-upload' : '&#xe021;',
			'imi-remove' : '&#xe022;',
			'imi-cog' : '&#xe023;',
			'imi-quotes-left' : '&#xe024;',
			'imi-user' : '&#xe025;',
			'imi-busy' : '&#xe026;',
			'imi-location' : '&#xe027;',
			'imi-box-add' : '&#xe028;',
			'imi-box-remove' : '&#xe029;',
			'imi-tv' : '&#xe02a;',
			'imi-tablet' : '&#xe02b;',
			'imi-mobile' : '&#xe02c;',
			'imi-mobile-2' : '&#xe02d;',
			'imi-screen' : '&#xe02e;',
			'imi-print' : '&#xe02f;',
			'imi-bullhorn' : '&#xe031;',
			'imi-next' : '&#xe032;',
			'imi-checkmark' : '&#xe033;',
			'imi-checkmark-2' : '&#xe034;',
			'imi-close' : '&#xe035;',
			'imi-minus' : '&#xe036;',
			'imi-plus' : '&#xe037;',
			'imi-pause' : '&#xe038;',
			'imi-stop' : '&#xe039;',
			'imi-shuffle' : '&#xe03a;',
			'imi-previous' : '&#xe03b;',
			'imi-play' : '&#xe03c;',
			'imi-pause-2' : '&#xe03d;',
			'imi-stop-2' : '&#xe03e;',
			'imi-play-2' : '&#xe03f;',
			'imi-exit' : '&#xe040;',
			'imi-enter' : '&#xe041;',
			'imi-console' : '&#xe042;',
			'imi-mail' : '&#xe043;',
			'imi-google-plus' : '&#xe044;',
			'imi-github' : '&#xe045;',
			'imi-signup' : '&#xe046;',
			'imi-cloud-upload' : '&#xe047;',
			'imi-cloud-download' : '&#xe048;',
			'imi-cloud' : '&#xe049;',
			'imi-bubble' : '&#xe04a;',
			'imi-stack' : '&#xe04b;',
			'imi-support' : '&#xe04c;',
			'imi-calculate' : '&#xe04d;',
			'imi-quill' : '&#xe04e;',
			'imi-pencil' : '&#xe04f;',
			'imi-library' : '&#xe050;',
			'imi-play-3' : '&#xe051;',
			'imi-spinner' : '&#xe052;',
			'imi-html5' : '&#xe053;',
			'imi-css3' : '&#xe054;',
			'imi-file-pdf' : '&#xe055;',
			'imi-file-openoffice' : '&#xe056;',
			'imi-file-excel' : '&#xe057;',
			'imi-file-zip' : '&#xe058;',
			'imi-file-powerpoint' : '&#xe059;',
			'imi-file-xml' : '&#xe05a;',
			'imi-file-css' : '&#xe05b;',
			'imi-tux' : '&#xe05c;',
			'imi-filter' : '&#xe05d;',
			'imi-tab' : '&#xe05e;',
			'imi-spam' : '&#xe05f;',
			'imi-checkmark-circle' : '&#xe060;',
			'imi-cancel-circle' : '&#xe061;',
			'imi-blocked' : '&#xe062;',
			'imi-info' : '&#xe063;',
			'imi-info-2' : '&#xe064;',
			'imi-warning' : '&#xe065;',
			'imi-notification' : '&#xe066;',
			'imi-question' : '&#xe067;',
			'imi-numbered-list' : '&#xe068;',
			'imi-menu' : '&#xe069;',
			'imi-menu-2' : '&#xe06a;',
			'imi-target' : '&#xe06b;',
			'imi-clock' : '&#xe06c;',
			'imi-alarm' : '&#xe06d;',
			'imi-download' : '&#xe030;',
			'imi-upload-2' : '&#xe06e;',
			'imi-feed' : '&#xe06f;',
			'imi-libreoffice' : '&#xe070;',
			'imi-wrench-2' : '&#xe071;',
			'imi-stats-2' : '&#xe072;',
			'imi-database' : '&#xe073;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/imi-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};